//
//  ExerciseName.swift
//  
//
//  Created by Paul Oggero on 03/09/2023.
//

import Foundation

public enum ExerciseName: String {
    case germanHang,
    tuckSTC,
    advTuckSTC,
    pikeSTC,
    tuckBL,
    advTuckBL,
    tuckFL,
    advTuckFL,
    OLBL,
    strBL,
    BL,
    BLPO,
    OLFL,
    strFL,
    FL,
    FLToInverted,
    HPFLtoInv,
    threeSixtyPull,
    germanHangPO,
    BAPUtoBL,
    HLtoBL,
    VRow,
    incRow,
    row,
    wideRow,
    LHang,
    archerRow,
    archerInRow,
    strOARow,
    OARow,
    tuckICM,
    tuckFLRow,
    advTuckFLRow,
    strFLRow,
    FLRow,
    ironCrossP,
    ironCross,
    ironCrossToBL,
    advancedIronCrossP,
    oneArmRow,
    oneArmPullUp,
    bodyweightRow,
    assistedPullUp,
    australianPullUp,
    typewriterRow,
    highRow,
    FLRaise,
    kneelingSAR,
    bandPullAparts,
    trxRows,
    chestSuppRows,
    reverseGripRows,
    singleArmDR,
    ringRows,
    invertedRowsWithFeetElevated,
    neutralGripRows,
    standardPullUp,
    mixedGripPullUp,
    clappingPullUp,
         chinUp,
         wideGripPullUp,
         commandoPullUp,
         LSitPullUp,
         weightedPullUp,
         typewriterPullUp,
         muscleUp,
         oneArmChinUp,
         passiveHang,
         assistedPassiveHang,
         activeHang,
         archHang,
         closeGripPullUp
    
    var translated: String {
        NSLocalizedString(self.rawValue, bundle: .module, comment: "Exercise name translated")
    }
}
